steps:
  # Build the container image with build arguments
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'REACT_APP_GOOGLE_CLIENT_ID=${_REACT_APP_GOOGLE_CLIENT_ID}'
      - '--build-arg'
      - 'REACT_APP_STRIPE_PUBLISHABLE_KEY=${_REACT_APP_STRIPE_PUBLISHABLE_KEY}'
      - '-t'
      - '${_GCR_HOSTNAME}/${PROJECT_ID}/${_SERVICE_NAME}:${COMMIT_SHA}'
      - '.'
  
  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_GCR_HOSTNAME}/${PROJECT_ID}/${_SERVICE_NAME}:${COMMIT_SHA}'
  
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_GCR_HOSTNAME}/${PROJECT_ID}/${_SERVICE_NAME}:${COMMIT_SHA}'
      - '--region'
      - '${_DEPLOY_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

# Substitution variables
substitutions:
  _GCR_HOSTNAME: asia-northeast1-docker.pkg.dev
  _SERVICE_NAME: nfp-front
  _DEPLOY_REGION: asia-northeast1
  _REACT_APP_GOOGLE_CLIENT_ID: '1072071838370-rsa39cnb30tmj37mdvilhpr1f0vdj5b0.apps.googleusercontent.com'
  _REACT_APP_STRIPE_PUBLISHABLE_KEY: 'pk_test_51S1qK2PSGxCREcZyTP9c4AgBB1bAJXY9Ul3WGkGc0sOL2kUWnPeYBUPEgbfmgNCBgN8NayoiREzP5scwXgfGxUZ300xJwFadAL'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY